/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author anahi
 */
import controller.DashboardController;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class DashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());

    private DashboardController controller;
    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
        controller = new DashboardController(this);
        controller.cargarDashboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalHabitantes = new javax.swing.JLabel();
        lblTotalViviendas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMunicipios = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLocalidades = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTiposVivienda = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblSeccion1 = new javax.swing.JLabel();
        lblSeccion = new javax.swing.JLabel();
        lblSeccion2 = new javax.swing.JLabel();
        lblSeccion3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTotalHabitantes.setText("Total Habitantes: 0");

        lblTotalViviendas.setText("Total Viviendas: 0");

        tblMunicipios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Municipio", "Habitantes"
            }
        ));
        jScrollPane2.setViewportView(tblMunicipios);

        tblLocalidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Localidad", "Habitantes"
            }
        ));
        jScrollPane3.setViewportView(tblLocalidades);

        tblTiposVivienda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tipo de Vivienda", "Habitantes"
            }
        ));
        jScrollPane1.setViewportView(tblTiposVivienda);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 204, 204));
        lblTitulo.setText("Dashboard del censo");

        lblSeccion1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblSeccion1.setText("Resumen General");

        lblSeccion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblSeccion.setText("Población por Municipio");

        lblSeccion2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblSeccion2.setText("Población por Localidad");

        lblSeccion3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblSeccion3.setText("Habitantes por Tipo de Vivienda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeccion1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSeccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeccion3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(btnRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblTotalHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(lblTotalViviendas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeccion1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalHabitantes)
                    .addComponent(lblTotalViviendas))
                .addGap(29, 29, 29)
                .addComponent(lblSeccion)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSeccion2)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblSeccion3)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnRegresar)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new MenuPrincipalFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    public void mostrarTotales(int totalHabitantes, int totalViviendas) {
        lblTotalHabitantes.setText("Total habitantes: " + totalHabitantes);
        lblTotalViviendas.setText("Total viviendas: " + totalViviendas);
    }

    public void mostrarHabitantesPorMunicipio(List<Object[]> datos) {
        llenarTabla(tblMunicipios, new String[]{"Municipio", "Habitantes"}, datos);
    }

    public void mostrarHabitantesPorLocalidad(List<Object[]> datos) {
        llenarTabla(tblLocalidades, new String[]{"Localidad", "Habitantes"}, datos);
    }

    public void mostrarHabitantesPorTipoVivienda(List<Object[]> datos) {
        llenarTabla(tblTiposVivienda, new String[]{"Tipo vivienda", "Habitantes"}, datos);
    }

    private void llenarTabla(javax.swing.JTable tabla, String[] columnas, List<Object[]> datos) {
        DefaultTableModel model = new DefaultTableModel(columnas, 0);

        for (Object[] fila : datos) {
            model.addRow(fila);
        }

        tabla.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblSeccion;
    private javax.swing.JLabel lblSeccion1;
    private javax.swing.JLabel lblSeccion2;
    private javax.swing.JLabel lblSeccion3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalHabitantes;
    private javax.swing.JLabel lblTotalViviendas;
    private javax.swing.JTable tblLocalidades;
    private javax.swing.JTable tblMunicipios;
    private javax.swing.JTable tblTiposVivienda;
    // End of variables declaration//GEN-END:variables
}
