/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
/**
 *
 * @author RZ_Ri
 */
public class MenuPrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName());

    /**
     * Creates new form MenuView
     */
    public MenuPrincipalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMunicipios = new javax.swing.JButton();
        btnViviendas = new javax.swing.JButton();
        btnHabitantes = new javax.swing.JButton();
        btnActividades = new javax.swing.JButton();
        btnLocalidades = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEscolaridades = new javax.swing.JButton();
        btnTipoVivienda = new javax.swing.JButton();
        btnSexos = new javax.swing.JButton();
        btnOcupaciones = new javax.swing.JButton();
        btnVivAct = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnHabitantesPorVivienda = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("REGISTROS");

        btnMunicipios.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnMunicipios.setText("Municipios");
        btnMunicipios.addActionListener(this::btnMunicipiosActionPerformed);

        btnViviendas.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnViviendas.setText("Viviendas");
        btnViviendas.addActionListener(this::btnViviendasActionPerformed);

        btnHabitantes.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnHabitantes.setText("Habitantes");
        btnHabitantes.addActionListener(this::btnHabitantesActionPerformed);

        btnActividades.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnActividades.setText("Actividades Economicas");
        btnActividades.addActionListener(this::btnActividadesActionPerformed);

        btnLocalidades.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnLocalidades.setText("Localidades");
        btnLocalidades.addActionListener(this::btnLocalidadesActionPerformed);

        btnCerrar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCerrar.setText("Cerrar Sesion");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("CENSO INEGI");

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("CATÁLOGOS");

        btnEscolaridades.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnEscolaridades.setText("Escolaridades");
        btnEscolaridades.addActionListener(this::btnEscolaridadesActionPerformed);

        btnTipoVivienda.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnTipoVivienda.setText("Tipos de Vivienda");
        btnTipoVivienda.addActionListener(this::btnTipoViviendaActionPerformed);

        btnSexos.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnSexos.setText("Sexo");
        btnSexos.addActionListener(this::btnSexosActionPerformed);

        btnOcupaciones.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnOcupaciones.setText("Ocupaciones");
        btnOcupaciones.addActionListener(this::btnOcupacionesActionPerformed);

        btnVivAct.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnVivAct.setText("Vivienda Actividad");
        btnVivAct.setToolTipText("");
        btnVivAct.addActionListener(this::btnVivActActionPerformed);

        jLabel4.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("RELACIONES");

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("SISTEMA");

        btnDashboard.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        btnReportes.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        btnHabitantesPorVivienda.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnHabitantesPorVivienda.setText("Habitantes por Vivienda");
        btnHabitantesPorVivienda.addActionListener(this::btnHabitantesPorViviendaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnViviendas, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(btnActividades))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel1)))
                        .addGap(139, 139, 139))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCerrar)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSexos, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTipoVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEscolaridades, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOcupaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jLabel3)))
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel4))
                            .addComponent(btnVivAct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(224, 224, 224))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnReportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnHabitantesPorVivienda)
                .addGap(64, 64, 64)
                .addComponent(btnDashboard)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViviendas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTipoVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSexos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEscolaridades, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOcupaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVivAct, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDashboard)
                    .addComponent(btnReportes)
                    .addComponent(btnHabitantesPorVivienda))
                .addGap(24, 24, 24)
                .addComponent(btnCerrar)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMunicipiosActionPerformed
        new MunicipioFrame().setVisible(true);
dispose();
    }//GEN-LAST:event_btnMunicipiosActionPerformed

    private void btnViviendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViviendasActionPerformed
        new ViviendaFrame().setVisible(true);
dispose();        
    }//GEN-LAST:event_btnViviendasActionPerformed

    private void btnHabitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitantesActionPerformed
        new HabitanteFrame().setVisible(true);
dispose();
    }//GEN-LAST:event_btnHabitantesActionPerformed

    private void btnActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActividadesActionPerformed
        new ActividadEconomicaFrame().setVisible(true);
dispose();
    }//GEN-LAST:event_btnActividadesActionPerformed

    private void btnLocalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalidadesActionPerformed
        new LocalidadFrame().setVisible(true);
dispose();
    }//GEN-LAST:event_btnLocalidadesActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
int op = JOptionPane.showOptionDialog(
        this,
        "¿Deseas cerrar sesión?",
        "Cerrar Sesión",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        new Object[]{"Sí, cerrar sesión", "No, cancelar"},
        "No, cancelar"
);

if(op == 0){
    new LoginFrame().setVisible(true);
    dispose();
}
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnEscolaridadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolaridadesActionPerformed
     new EscolaridadFrame().setVisible(true);
dispose();
    }//GEN-LAST:event_btnEscolaridadesActionPerformed

    private void btnTipoViviendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoViviendaActionPerformed
    new TipoViviendaFrame().setVisible(true);
dispose();
    }//GEN-LAST:event_btnTipoViviendaActionPerformed

    private void btnSexosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSexosActionPerformed
      new SexoFrame().setVisible(true);
dispose();
    }//GEN-LAST:event_btnSexosActionPerformed

    private void btnOcupacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcupacionesActionPerformed
        new OcupacionFrame().setVisible(true);
dispose();
    }//GEN-LAST:event_btnOcupacionesActionPerformed

    private void btnVivActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVivActActionPerformed
        new ViviendaActividadFrame().setVisible(true);
dispose();
    }//GEN-LAST:event_btnVivActActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
       new DashboardFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        new ReportesFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnHabitantesPorViviendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitantesPorViviendaActionPerformed
        new HabitantesPorViviendaFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHabitantesPorViviendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActividades;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnEscolaridades;
    private javax.swing.JButton btnHabitantes;
    private javax.swing.JButton btnHabitantesPorVivienda;
    private javax.swing.JButton btnLocalidades;
    private javax.swing.JButton btnMunicipios;
    private javax.swing.JButton btnOcupaciones;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSexos;
    private javax.swing.JButton btnTipoVivienda;
    private javax.swing.JButton btnVivAct;
    private javax.swing.JButton btnViviendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
