/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author anahi
 */
import controller.ReportesController;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class ReportesFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportesFrame.class.getName());

    private ReportesController controller;
    /**
     * Creates new form ReportesFrame
     */
    public ReportesFrame() {
        initComponents();
        controller = new ReportesController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        btnHabMunicipio = new javax.swing.JButton();
        btnHabLocalidad = new javax.swing.JButton();
        btnVivMunicipio = new javax.swing.JButton();
        btnHabTipoVivienda = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblSeccion1 = new javax.swing.JLabel();
        lblSeccion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Concepto", "Total"
            }
        ));
        jScrollPane2.setViewportView(tblReporte);

        btnHabMunicipio.setText("Habitantes por Municipio");
        btnHabMunicipio.addActionListener(this::btnHabMunicipioActionPerformed);

        btnHabLocalidad.setText("Habitantes por Localidad");
        btnHabLocalidad.addActionListener(this::btnHabLocalidadActionPerformed);

        btnVivMunicipio.setText("Viviendas por Municipio");
        btnVivMunicipio.addActionListener(this::btnVivMunicipioActionPerformed);

        btnHabTipoVivienda.setText("Habitantes por Tipo de Vivienda");
        btnHabTipoVivienda.addActionListener(this::btnHabTipoViviendaActionPerformed);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 204, 204));
        lblTitulo.setText("Reportes del censo");

        lblSeccion1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblSeccion1.setText("Seleccione un reporte");

        lblSeccion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblSeccion.setText("Resultado del Reporte");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHabMunicipio)
                    .addComponent(btnHabLocalidad))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(btnVivMunicipio)
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnHabTipoVivienda)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeccion1)
                            .addComponent(lblSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(btnRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeccion1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHabTipoVivienda)
                    .addComponent(btnHabMunicipio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVivMunicipio)
                    .addComponent(btnHabLocalidad))
                .addGap(26, 26, 26)
                .addComponent(btnRegresar)
                .addGap(18, 18, 18)
                .addComponent(lblSeccion)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHabMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabMunicipioActionPerformed
        controller.reporteHabitantesPorMunicipio();
    }//GEN-LAST:event_btnHabMunicipioActionPerformed

    private void btnHabLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabLocalidadActionPerformed
        controller.reporteHabitantesPorLocalidad();
    }//GEN-LAST:event_btnHabLocalidadActionPerformed

    private void btnVivMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVivMunicipioActionPerformed
        controller.reporteViviendasPorMunicipio();
    }//GEN-LAST:event_btnVivMunicipioActionPerformed

    private void btnHabTipoViviendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabTipoViviendaActionPerformed
        controller.reporteHabitantesPorLocalidad();
    }//GEN-LAST:event_btnHabTipoViviendaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new MenuPrincipalFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

     public void mostrarReporte(String titulo, String[] columnas, List<Object[]> datos) {
        lblTitulo.setText(titulo);

        DefaultTableModel model = new DefaultTableModel(columnas, 0);

        for (Object[] fila : datos) {
            model.addRow(fila);
        }

        tblReporte.setModel(model);
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportesFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHabLocalidad;
    private javax.swing.JButton btnHabMunicipio;
    private javax.swing.JButton btnHabTipoVivienda;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVivMunicipio;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSeccion;
    private javax.swing.JLabel lblSeccion1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables
}
